INSERT INTO appointments (        appointment_id,
                                  doctor_email,
                                  patient_email,
                                  hospital_name,
                                  date,
                                  duration,
                                  status)
VALUES (nextval('ehealth_sequence'),
        'polly@email.com', 'emily@email.com',
        'Medpark International Hospital',
        '2022-04-20 10:20:00', 15, 'DONE'),
    (nextval('ehealth_sequence'),
        'polly@email.com', 'emily@email.com',
        'Medpark International Hospital',
        '2022-04-20 11:30:00', 30, 'DECLINED'),
    (nextval('ehealth_sequence'),
        'tommy@email.com', 'emily@email.com',
        'Medpark International Hospital',
        '2022-05-10 14:00:00', 60, 'REQUESTED'),
    (nextval('ehealth_sequence'),
        'tommy@email.com', 'emily@email.com',
        'Repromed',
        '2022-05-01 12:00:00', 45, 'APPROVED');