INSERT INTO appointments (        appointment_id,
                                  doctor_email,
                                  patient_email,
                                  hospital_name,
                                  start_date,
                                  end_date,
                                  status)
VALUES (nextval('ehealth_sequence'),
        'kotkatea@gmail.com', 'ecaterina.cotelnic@isa.utm.md',
        'Medpark International Hospital',
        '2022-04-20 10:20:00','2022-04-20 10:40:00', 'DONE'),
    (nextval('ehealth_sequence'),
        'kotkatea@gmail.com', 'ecaterina.cotelnic@isa.utm.md',
        'Medpark International Hospital',
        '2022-04-20 11:30:00','2022-04-20 12:00:00', 'DECLINED'),
    (nextval('ehealth_sequence'),
        'tommy@email.com', 'ecaterina.cotelnic@isa.utm.md',
        'Medpark International Hospital',
        '2022-05-10 14:00:00', '2022-05-10 16:00:00', 'REQUESTED'),
    (nextval('ehealth_sequence'),
        'tommy@email.com', 'ecaterina.cotelnic@isa.utm.md',
        'Repromed',
        '2022-05-01 12:00:00', '2022-05-01 12:20:00', 'APPROVED');